version: '3.8'

services:
  postgres-db:
    image: postgres:17.0
    environment:
      POSTGRES_USER: traore
      POSTGRES_PASSWORD: root
      POSTGRES_DB: dbwebflux
    ports:
      - "5432:5432"  # The port 5432 exposed to the host
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  postgres_data:

networks:
  app-network:
