version: '3.8'
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: dbwebflux
      POSTGRES_USER: traore
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
