spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:student_bd
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: always

      # pour bien comprendre init avec data sql ou create tab by schema
    #https://www.baeldung.com/spring-boot-data-sql-and-schema-sql


#http://localhost:8080/h2-console/