server:
  port: 8081
spring:
  messages:
     basename: messages
  #bdd H2
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:student_bd
    driverClassName: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    defer-datasource-initialization: true
  sql:
    init:
      mode: NEVER #always

      # pour bien comprendre init avec data sql ou create tab by schema
    #https://www.baeldung.com/spring-boot-data-sql-and-schema-sql

logging:
  level:
    datasource-query-logger: INFO
    org:
      springframework:
        data: DEBUG
        security: DEBUG
        web: ERROR
        orm.jpa.JpaTransactionManager: debug  #va notify en cas de probleme dans transaction en log
        boot.autoconfiguration.h2: INFO #info sur bdd

#      hibernate: DEBUG
#      apache:
#        commons:
#          dbcp2: DEBUG
  ## genereted file log
  path: concretepage/logs




#http://localhost:8081/h2-console/