
-- Insertion des rôles avec "WHERE NOT EXISTS"
INSERT INTO ROLE(ROLE_NAME)
SELECT 'ROLE_ADMIN'
WHERE NOT EXISTS (SELECT 1 FROM ROLE WHERE ROLE_NAME = 'ROLE_ADMIN');

INSERT INTO ROLE(ROLE_NAME)
SELECT 'ROLE_USER'
WHERE NOT EXISTS (SELECT 1 FROM ROLE WHERE ROLE_NAME = 'ROLE_USER');

-- Insertion des utilisateurs avec "WHERE NOT EXISTS"
INSERT INTO UTILISATEUR(USERNAME, USER_PASSWORD, USER_ACTIVE)
SELECT 'admin', 'admin', 1
WHERE NOT EXISTS (SELECT 1 FROM UTILISATEUR WHERE USERNAME = 'admin');

INSERT INTO UTILISATEUR(USERNAME, USER_PASSWORD, USER_ACTIVE)
SELECT 'login2', 'user', 1
WHERE NOT EXISTS (SELECT 1 FROM UTILISATEUR WHERE USERNAME = 'login2');

INSERT INTO UTILISATEUR(USERNAME, USER_PASSWORD, USER_ACTIVE)
SELECT 'login3', 'user1', 0
WHERE NOT EXISTS (SELECT 1 FROM UTILISATEUR WHERE USERNAME = 'login3');

-- Associer les utilisateurs aux rôles avec "WHERE NOT EXISTS"
INSERT INTO USER_ROLE(USER_ID, ROLE_ID)
SELECT (SELECT USER_ID FROM UTILISATEUR WHERE USERNAME = 'admin'),
       (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = 'ROLE_ADMIN')
WHERE NOT EXISTS (
    SELECT 1 FROM USER_ROLE
    WHERE USER_ID = (SELECT USER_ID FROM UTILISATEUR WHERE USERNAME = 'admin')
    AND ROLE_ID = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = 'ROLE_ADMIN')
);

INSERT INTO USER_ROLE(USER_ID, ROLE_ID)
SELECT (SELECT USER_ID FROM UTILISATEUR WHERE USERNAME = 'admin'),
       (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = 'ROLE_USER')
WHERE NOT EXISTS (
    SELECT 1 FROM USER_ROLE
    WHERE USER_ID = (SELECT USER_ID FROM UTILISATEUR WHERE USERNAME = 'admin')
    AND ROLE_ID = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = 'ROLE_USER')
);

INSERT INTO USER_ROLE(USER_ID, ROLE_ID)
SELECT (SELECT USER_ID FROM UTILISATEUR WHERE USERNAME = 'login2'),
       (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = 'ROLE_USER')
WHERE NOT EXISTS (
    SELECT 1 FROM USER_ROLE
    WHERE USER_ID = (SELECT USER_ID FROM UTILISATEUR WHERE USERNAME = 'login2')
    AND ROLE_ID = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = 'ROLE_USER')
);

INSERT INTO USER_ROLE(USER_ID, ROLE_ID)
SELECT (SELECT USER_ID FROM UTILISATEUR WHERE USERNAME = 'login3'),
       (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = 'ROLE_USER')
WHERE NOT EXISTS (
    SELECT 1 FROM USER_ROLE
    WHERE USER_ID = (SELECT USER_ID FROM UTILISATEUR WHERE USERNAME = 'login3')
    AND ROLE_ID = (SELECT ROLE_ID FROM ROLE WHERE ROLE_NAME = 'ROLE_USER')
);

-- Insertion des départements avec------------------------------------------------------------------------------------
-- Insertion des départements avec "WHERE NOT EXISTS"
INSERT INTO DEPARTMENT(ID, NAME, LOCATION)
SELECT 1, 'INFORMATIQUE', 'YourLocation'
WHERE NOT EXISTS (SELECT 1 FROM DEPARTMENT WHERE NAME = 'INFORMATIQUE');

-- Insertion des étudiants avec "WHERE NOT EXISTS"---------------------------------------------------------------------
INSERT INTO STUDENT(ID, LAST_NAME, FIRST_NAME, SEXE, EMAIL, DEPARTMENT_ID,DATE_OF_BIRTH,ENROLLMENT_DATE,PHONE)
SELECT 1, 'tra', 'kaba', 'M', 'kaba@gmail.com', 1,'1990-01-01','2024-01-01','+33755052865'
WHERE NOT EXISTS (SELECT 1 FROM STUDENT WHERE EMAIL = 'kaba@gmail.com');

INSERT INTO STUDENT(ID, LAST_NAME, FIRST_NAME, SEXE, EMAIL, DEPARTMENT_ID,DATE_OF_BIRTH,ENROLLMENT_DATE,PHONE)
SELECT 2,'keita', 'mamady', 'M', 'keita@gmail.com', 1,'1992-01-01','2024-01-01','+33755052865'
WHERE NOT EXISTS (SELECT 1 FROM STUDENT WHERE EMAIL = 'keita@gmail.com');

INSERT INTO STUDENT(ID, LAST_NAME, FIRST_NAME, SEXE, EMAIL, DEPARTMENT_ID,DATE_OF_BIRTH,ENROLLMENT_DATE,PHONE)
SELECT 3,'tra', 'kaman', 'M', 'kaman@gmail.com', 1,'1993-01-01','2024-01-01','+33755052865'
WHERE NOT EXISTS (SELECT 1 FROM STUDENT WHERE EMAIL = 'kaman@gmail.com');

INSERT INTO STUDENT(ID, LAST_NAME, FIRST_NAME, SEXE, EMAIL, DEPARTMENT_ID,DATE_OF_BIRTH,ENROLLMENT_DATE,PHONE)
SELECT 5,'tra', 'koman', 'M', 'koman@gmail.com', 1,'1998-01-01','2024-01-01','+33755052865'
WHERE NOT EXISTS (SELECT 1 FROM STUDENT WHERE EMAIL = 'koman@gmail.com');

-- Insertion des enseignants avec "WHERE NOT EXISTS"--------------------------------------------------------------------------
INSERT INTO TEACHER(ID,LAST_NAME, FIRST_NAME, SEXE, EMAIL, DEPARTMENT_ID)
SELECT 1,'tra', 'kaman', 'M', 'kaman@gmail.com', 1
WHERE NOT EXISTS (SELECT 1 FROM TEACHER WHERE EMAIL = 'kaman@gmail.com');

INSERT INTO TEACHER(ID,LAST_NAME, FIRST_NAME, SEXE, EMAIL, DEPARTMENT_ID)
SELECT 2,'tra', 'koman', 'M', 'koman@gmail.com', 1
WHERE NOT EXISTS (SELECT 1 FROM TEACHER WHERE EMAIL = 'koman@gmail.com');

-- Insertion des cours avec "WHERE NOT EXISTS"
INSERT INTO COURSE(ID,TITLE, DESCRIPTION, COEFFICIENT, TEACHER_ID)
SELECT 1,  'Physique', 'physique matière', 3, 1
WHERE NOT EXISTS (SELECT 1 FROM COURSE WHERE TITLE = 'Physique');

INSERT INTO COURSE(ID,TITLE, DESCRIPTION, COEFFICIENT, TEACHER_ID)
SELECT 2, 'MATHS', 'Mathematiques', 4, 2
WHERE NOT EXISTS (SELECT 1 FROM COURSE WHERE TITLE = 'MATHS');

INSERT INTO COURSE(ID,TITLE, DESCRIPTION, COEFFICIENT, TEACHER_ID)
SELECT 3,'Chimie', 'Chimie important', 3, 2
WHERE NOT EXISTS (SELECT 1 FROM COURSE WHERE TITLE = 'Chimie');

-- Association des étudiants aux cours avec "WHERE NOT EXISTS"

INSERT INTO STUDENT_COURSE(STUDENT_ID, COURSE_ID)
SELECT 1, 1
WHERE NOT EXISTS (SELECT 1 FROM STUDENT_COURSE WHERE STUDENT_ID = 1 AND COURSE_ID = 1);

INSERT INTO STUDENT_COURSE(STUDENT_ID, COURSE_ID)
SELECT 1, 2
WHERE NOT EXISTS (SELECT 1 FROM STUDENT_COURSE WHERE STUDENT_ID = 1 AND COURSE_ID = 2);

INSERT INTO STUDENT_COURSE(STUDENT_ID, COURSE_ID)
SELECT 2, 1
WHERE NOT EXISTS (SELECT 1 FROM STUDENT_COURSE WHERE STUDENT_ID = 2 AND COURSE_ID = 1);

INSERT INTO STUDENT_COURSE(STUDENT_ID, COURSE_ID)
SELECT 5, 2
WHERE NOT EXISTS (SELECT 1 FROM STUDENT_COURSE WHERE STUDENT_ID = 5 AND COURSE_ID = 2);

-- Commit des transactions
COMMIT;
